import Head from "next/head";
import NewPollForm from "../components/new_poll/new_poll_form";

export default function NewPoll() {
  return (
    <>
      <Head>
        <title>PollMaster - Nova poll</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div
        className="container px-4 col-sm-12 col-md-12 col-lg-8 col-xl-7"
        style={{ maxWidth: 1000 }}
      >
        <NewPollForm />
      </div>
    </>
  );
}
